[env]
framework = arduino
platform = espressif32
board = esp32dev
monitor_speed = 115200
upload_speed = 115200
board_build.filesystem = littlefs

[env:esp32_real]
build_flags =
    -DMODE_REAL=1
    -DCORE_DEBUG_LEVEL=2
lib_deps =
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    ArduinoJson
    https://github.com/me-no-dev/AsyncTCP.git

[env:esp32_sim]
build_flags =
    -DMODE_SIM=1
    -DCORE_DEBUG_LEVEL=2
lib_deps =
    ArduinoJson
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
